### ISSUE TITLE
你好,我想把广播中间件的发送间隔调的快一点,该修改哪里的参数啊？

### ISSUE THREAD

**Issue by little-jary** [czasg/Pywss#1]
你好,我想把广播中间件的发送间隔调的快一点,该修改哪里的参数啊？

**Comment by CzaOrz** [comment]
不好意思哈，最近在搞minitools，没看到消息
源码middlewares.py - 145 行
time.sleep(PublicConfig.RADIO_TIME)  # 这里是执行时延的代码，更改这里就行了

具体代码：已更新了examples/example2.py
from pywss import PublicConfig
PublicConfig.RADIO_TIME = 1

**Comment by CzaOrz** [comment]
> 你好，我想把广播中间件的发送间隔调的快一点，该修改哪里的参数啊？
不好意思哈，最近在从事minitools，没看到消息
源码middlewares.py-145行
time.sleep（PublicConfig.RADIO_TIME）＃这里是执行时延的代码，更改这里就行了

具体代码：
已从pywss 更新了examples / example2.py import PublicConfig 
PublicConfig.RADIO_TIME = 1

**Comment by CzaOrz** [comment]
不好意思哈，最近在写minitools，没看到消息
源码middlewares.py-145行
time.sleep（PublicConfig.RADIO_TIME）＃这里是执行时延的代码，更改这里就行了

具体代码：
已从pywss 更新了examples / example2.py import PublicConfig 
PublicConfig.RADIO_TIME = 1

**Comment by CzaOrz** [comment]
不好意思哈，最近在写minitools，没看到消息
源码middlewares.py-145行
time.sleep(PublicConfig.RADIO_TIME)  ＃这里是执行时延的代码，更改这里就行了

具体代码：已更新了examples / example2.py
from pywss import PublicConfig
PublicConfig.RADIO_TIME = 1

**Comment by tomjary** [comment]
多谢大佬
