### ISSUE TITLE
多进程问题

### ISSUE THREAD

**Issue by 2331442542** [czasg/pywss#157]
我看你的chat demo，python的部署一般是多进程，每个进程都有自己pool，怎么让它们能通信呢，有没有成熟的解决方案

**Comment by czasg** [comment]
不同进程之间的通信，可以有很多种方式。

以 RabbitMQ 为例，可以通过广播的方式，实现不同进程之间通信。
![image](https://github.com/czasg/pywss/assets/44974561/db302f0d-fc06-4536-94da-e52e339da5fc)
用户A：发送消息
服务器A：推送消息
RMQ：广播消息
服务器B、C：接收消息
用户B、C：接收消息
