### ISSUE TITLE
Simple walkthrough needed to setup demo apps on apache2

### ISSUE THREAD

**Issue by crazydev-pk** [czasg/pywss#186]
Dear,

You have done a great job for integrating luckysheet. I can successfully run demo apps on local computer without an error. I'm trying to deploy demo to a Ubuntu server running apache2 without any luck. 

Can you please spare some time and make a simple walkthrough to deploy PYWSS/Demo App on a domain? Let say mydomain.com/sheet may run (localhost:8080/static/luckysheet.html.

Thank you,
Ahmad.

**Comment by czasg** [comment]
Your main problem is probably how to configure the websocket reverse proxy on apache2.  
 I have updated a demo（Window）, you can refer to it.
- https://github.com/czasg/pywss/tree/master/demo/apache/luckysheet

**Comment by crazydev-pk** [comment]
Bundle of thanks for your consideration. Can you please suggest how can we show username in lucky sheet collaborative editing? These users can be logged in users through a login form? Any suggestions on this please.

**Comment by crazydev-pk** [comment]
I can see SSO demo have user registration and login functionality. I will try to merge it with luckysheet demo. So that user have to login to access sheet. 
If you can spare some time, it will not take you much time to merge these. and create a new demo, only if you can spare some time easily.

Thank you Bro.

**Comment by crazydev-pk** [comment]
Brother one more thing, How can I insert a cell value (row and column) directly into luckysheet database? and If a value is inserted in the database, will it be synched with opened sheet?

**Comment by czasg** [comment]
> Bundle of thanks for your consideration. I will check apache demo and will implement it.
> 
> Can you please suggest how can we show username in lucky sheet collaborative editing? These users can be logged in users through a login form? Any suggestions on this please.

Refer to official documents：
- https://dream-num.github.io/LuckysheetDocs/guide/operate.html#backend-return-format

the filed `username` of luckysheet-websocket-data will meet your needs.

**Comment by czasg** [comment]
I think you might need a demo like this:

- Support user login and registration
- Supports the creation of persistent luckysheet documents
- Show username in luckysheet collaborative editing

I will update this demo later in my free time

**Comment by crazydev-pk** [comment]
Great, I will be waiting for the demo.

**Comment by crazydev-pk** [comment]
> Brother one more thing, How can I insert a cell value (row and column) directly into luckysheet database? and If a value is inserted in the database, will it be synched with opened sheet?

Well, idea is that if we use sheet for a data collected from a form, instead of putting data manually to the sheet, if we can directly insert into sheet database. And if sheet is open, will this database change be synched with sheet? I need your opinion on this please.

**Comment by crazydev-pk** [comment]
Here is some log data, demo application was running and stopped loading sheet.
"time="2023-10-12 18:20:29.622508" level=warning msg="No Handler" route="CONNECT/google.com:443" 
time="2023-10-12 19:20:38.076662" level=warning msg="No Handler" route="CONNECT/google.com:443" 
time="2023-10-12 20:44:43.655381" level=warning msg="No Handler" route="POST/cgi-bin/luci/;stok=/locate" 
time="2023-10-12 22:04:27.835750" level=error msg="bad request header b'\x00\x93\x00c\x00\x15\x00\x12\x00\x0f\x00\x0c\x00\x1a\x00b\x00\t\x00a\x00e\x00d\x00`\x00\x1
4\x00\x11\x00\x0e\x00\x0b\x00\x19\x00\x08\x00\x06\x00\x17\x00\x03\xc0\x15\xc0\x10\xc0\x06\xc0\x0b\xc0\x01\x00;\x00\x02\x00\x01\x00\xff\x02\x01\x00\x00\x93\x00\x00\
x00\x13\x00\x11\x00\x00\x0e108.181.164.79\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n'" route="Ý ÙËÔF¤9/S'ï+0#ï(Cg"

any suggestions on this issue please?

**Comment by crazydev-pk** [comment]
Some more logs
time="2023-10-12 08:16:59.211732" level=warning msg="704bb5bd-f324-43f8-a243-295a823f15dd exit" route="GET/luckysheet/api/updateUrl" 
time="2023-10-12 08:18:05.843678" level=warning msg="d100b46d-d351-45ff-86bb-55618f9f2c8b exit" route="GET/luckysheet/api/updateUrl" 
time="2023-10-12 08:18:06.964031" level=warning msg="No Handler" route="GET/favicon.ico" 
time="2023-10-12 08:19:22.629968" level=warning msg="5404dbc8-84fc-4c0d-b889-cf06b9d54096 exit" route="GET/luckysheet/api/updateUrl" 
time="2023-10-12 08:21:01.204785" level=warning msg="97d62966-64ed-49ea-a6af-fb5a89ddb765 exit" route="GET/luckysheet/api/updateUrl"

**Comment by czasg** [comment]
> > Brother one more thing, How can I insert a cell value (row and column) directly into luckysheet database? and If a value is inserted in the database, will it be synched with opened sheet?
> 
> Well, idea is that if we use sheet for a data collected from a form, instead of putting data manually to the sheet, if we can directly insert into sheet database. And if sheet is open, will this database change be synched with sheet? I need your opinion on this please.

A normal process would be for the user to work on a luckysheet form, and then the back end would receive the data and store it in a database.
- If there are other online users, a copy of the data is synchronized to them, so that the user can receive the modified data of other users.
- If new users come in, they can read the latest database data to perform initialization, so that they see the same table data.

However, if you modify the database directly, the user will not be able to perceive the data change unless you explicitly notify him, as is the normal process.

**Comment by czasg** [comment]
> Here is some log data, demo application was running and stopped loading sheet. "time="2023-10-12 18:20:29.622508" level=warning msg="No Handler" route="CONNECT/google.com:443" time="2023-10-12 19:20:38.076662" level=warning msg="No Handler" route="CONNECT/google.com:443" time="2023-10-12 20:44:43.655381" level=warning msg="No Handler" route="POST/cgi-bin/luci/;stok=/locate" time="2023-10-12 22:04:27.835750" level=error msg="bad request header b'\x00\x93\x00c\x00\x15\x00\x12\x00\x0f\x00\x0c\x00\x1a\x00b\x00\t\x00a\x00e\x00d\x00`\x00\x1 4\x00\x11\x00\x0e\x00\x0b\x00\x19\x00\x08\x00\x06\x00\x17\x00\x03\xc0\x15\xc0\x10\xc0\x06\xc0\x0b\xc0\x01\x00;\x00\x02\x00\x01\x00\xff\x02\x01\x00\x00\x93\x00\x00 x00\x13\x00\x11\x00\x00\x0e108.181.164.79\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n'" route="Ý ÙËÔF¤9/S'ï+0#ï(Cg"
> 
> any suggestions on this issue please?

The http protocol resolution is abnormal. Check whether a NON-HTTP request is used.

**Comment by czasg** [comment]
> I think you might need a demo like this:
> 
> * Support user login and registration
> * Supports the creation of persistent luckysheet documents
> * Show username in luckysheet collaborative editing
> 
> I will update this demo later in my free time

I made some updates, refer to this demo：
- https://github.com/czasg/pywss/blob/master/demo/luckysheet-manager/README-en.md

**Comment by crazydev-pk** [comment]
> > I think you might need a demo like this:
> > 
> > * Support user login and registration
> > * Supports the creation of persistent luckysheet documents
> > * Show username in luckysheet collaborative editing
> > 
> > I will update this demo later in my free time
> 
> I made some updates, refer to this demo：
> 
> * https://github.com/czasg/pywss/blob/master/demo/luckysheet-manager/README-en.md

That is great brother, I will look into it.

**Comment by crazydev-pk** [comment]
> > > Brother one more thing, How can I insert a cell value (row and column) directly into luckysheet database? and If a value is inserted in the database, will it be synched with opened sheet?
> > 
> > 
> > Well, idea is that if we use sheet for a data collected from a form, instead of putting data manually to the sheet, if we can directly insert into sheet database. And if sheet is open, will this database change be synched with sheet? I need your opinion on this please.
> 
> A normal process would be for the user to work on a luckysheet form, and then the back end would receive the data and store it in a database.
> 
> * If there are other online users, a copy of the data is synchronized to them, so that the user can receive the modified data of other users.
> * If new users come in, they can read the latest database data to perform initialization, so that they see the same table data.
> 
> However, if you modify the database directly, the user will not be able to perceive the data change unless you explicitly notify him, as is the normal process.

Bundle of thanks for the suggestion. I will work on it.

**Comment by crazydev-pk** [comment]
time="2023-10-13 01:46:49.285271" level=error msg=traceback route="POST/luckysheet/api/loadUrl" error="Traceback (most recent call last): 
  File "C:\paython\corby\venv\lib\site-packages\pywss\__init__.py", line 673, in handler_request
    ctx.next()
  File "C:\python\corby\venv\lib\site-packages\pywss\__init__.py", line 78, in next
    self._handlers[index](self)
  File "C:\python\corby\api\load.py", line 10, in load
    data = document["data"]
TypeError: 'NoneType' object is not subscriptable"
time="2023-10-13 01:46:49.864246" level=error msg=traceback route="POST/luckysheet/api/loadUrl" error="Traceback (most recent call last): 
    ctx.next()
  File "C:\python\corby\venv\lib\site-packages\pywss\__init__.py", line 78, in next
    self._handlers[index](self)
  File "C:\payments\corby\api\load.py", line 10, in load
    data = document["data"]
TypeError: 'NoneType' object is not subscriptable"

**Comment by crazydev-pk** [comment]
> > I think you might need a demo like this:
> > 
> > * Support user login and registration
> > * Supports the creation of persistent luckysheet documents
> > * Show username in luckysheet collaborative editing
> > 
> > I will update this demo later in my free time
> 
> I made some updates, refer to this demo：
> 
> * https://github.com/czasg/pywss/blob/master/demo/luckysheet-manager/README-en.md

Requirements files need to add some libraries. If one don't have installed it will result in an error.

**Comment by czasg** [comment]
972542655@qq.com

**Comment by crazydev-pk** [comment]
Brother if a cell have number values e.g. 0004356, this value is being saved as 4356, how can we save correct values? Any fix for this.

**Comment by czasg** [comment]
You can convert `int` to `string`.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "czasg/pywss"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月16日(星期一) 晚上9:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [czasg/pywss] Simple walkthrough needed to setup demo apps on apache2 (Issue #186)





 
Brother if a cell have number values e.g. 0004356, this value is being saved as 4356, how can we save correct values? Any fix for this.

**Comment by crazydev-pk** [comment]
Brother after implementing security getting timeout error:

pymongo.errors.ServerSelectionTimeoutError: localhost:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 652e1e857490ac8ac50df01b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('localhost:27017: timed out',)>]>

Any suggestion on this please.

**Comment by crazydev-pk** [comment]
Everything has been settled now. Thanks for your help and great work. :)
