### ISSUE TITLE
你好，我想让服务端主动向客户端推送消息该怎么做？

### ISSUE THREAD

**Issue by jaryf** [czasg/Pywss#2]
我想实现一个功能就是服务端主动向客户端推送消息。
例如每隔0.1秒向客户端发一条消息:"hello, client!"
这个功能用您的这个该怎么实现？

**Comment by CzaOrz** [comment]
你好，服务端主动向客户端推送，可以参考第二个案例。（我发现github消息通知很有问题....）
https://github.com/CzaOrz/Pywss/blob/master/examples/example2.py

间隔0.1s的话，需要修改下配置
from pywss import PublicConfig
PublicConfig.RADIO_TIME = 0.1  # 控制广播中间件间隔为0.1s

发送指定消息则需要修改
from pywss import RadioMiddleware
class Radio(RadioMiddleware):
    @classmethod
    def process_data(cls):
        return "hello, client!"  # 此处返回指定消息。

**Comment by tomjary** [comment]
真的是太棒了！

**Comment by liuzaozao7799** [comment]
不能像ws.send()一样发送消息吗？

**Comment by CzaOrz** [comment]
> 不能像ws.send()一样发送消息吗？

可以，参考 example1的参数简介部分：
* 参数简介
    * /test/example/1: 请求路径path
    * request: socket句柄，包括发送和接受数据。 
        * 接受数据 request.ws_recv(1024)
        * 发送数据 request.ws_send(data) 
    * data: 传递过来的数据

发送消息可以使用 `request.ws_send(data)`
对所有用户发送可调用 `request.conn.send_to_all(data)`

**Comment by liuzaozao7799** [comment]
> > 不能像ws.send()一样发送消息吗？
> 
> 可以，参考 example1的参数简介部分：
> 
> * 参数简介
>   
>   * /test/example/1: 请求路径path
>   * request: socket句柄，包括发送和接受数据。
>     
>     * 接受数据 request.ws_recv(1024)
>     * 发送数据 request.ws_send(data)
>   * data: 传递过来的数据
> 
> 发送消息可以使用 `request.ws_send(data)`
> 对所有用户发送可调用 `request.conn.send_to_all(data)`

了解！谢谢。还有是不是服务端返回的数据如果不是字符串就会自动断开连接吗？连接有什么不稳定因素吗？因为我的服务端是一个爬虫，我发现爬着爬着连接会断开。有什么方法维持这种连接吗？

**Comment by CzaOrz** [comment]
websocket本身就是长连接。如果异常断开，这个得看日志，不好判断...

ws_send的源码部分：
```python
    def ws_send(self, data, flags: int = ...):
        self.sendall(WebSocketProtocol.encode_msg(json.dumps(data, ensure_ascii=False).encode('utf-8')))
```
传递的数据，我会帮他转为json，并不是只能传递str
所以你看下是不是爬虫传递了什么类型的数据，导致此处报错。

提供下报错日志也是可以的。

**Comment by CzaOrz** [comment]
不好意思，我想起来了，这是我当时留下得问题。
此处转码报错会直接断开连接...

**Comment by liuzaozao7799** [comment]
> websocket本身就是长连接。如果异常断开，这个得看日志，不好判断...
> 
> ws_send的源码部分：
> 
> ```python
>     def ws_send(self, data, flags: int = ...):
>         self.sendall(WebSocketProtocol.encode_msg(json.dumps(data, ensure_ascii=False).encode('utf-8')))
> ```
> 
> 传递的数据，我会帮他转为json，并不是只能传递str
> 所以你看下是不是爬虫传递了什么类型的数据，导致此处报错。
> 
> 提供下报错日志也是可以的。

我应该明白了，有一些比较微妙的地方，首先我用的是这个格式发送数据给客户端：
```
@ws.route('/test/example/1/1')
def example_1(request, data):
    return data + ' - data from pywss'
```
所以①如果存在多个客户端时，return时好像会直接断开连接，不是异常断开，客户端的onerror没有触发；
②然后还有一个就是您刚说的这里传输数据的类型，对于return这里好像只能是str；
③如果我爬虫出错，终止了，也会断开连接，这个应该是爬虫程序的问题。
然后刚刚我使用了ws_send()方法 ，可以。谢谢！（顺便问一句，心跳机制对于这样的长连接还有必要吗？可能可以解决我的问题③）

**Comment by CzaOrz** [comment]
首先万分抱歉，日志部分被我干掉了，所以服务端可能基本看不到异常日志。

然后：
1、return后断开连接的问题，我大概知道了原因了，正再处理。我打算：
* 如果是json转码出错，我会捕获日志并提示。此时不会断开连接。
* 如果是客户端断开连接，则打印相关日志，断开连接。
* 如果服务端异常，则捕获日志并打印。断开连接。

2、传输类型是可序列化的数据结构就行，比如：dict和list。
```
@ws.route('/test/example/1/1')
def example_1(request, data):
    return {'hello': 'world'}

@ws.route('/test/example/1/2')
def example_1(request, data):
    return ['hello', 'world']
```

3、我有点好奇，你是在用爬虫爬这个服务端吗？
心跳机制这种肯定是有必要的，不过我近期最大的目标，是研究concurrent、asyncio，我想尝试能不能把框架改异步！

**Comment by liuzaozao7799** [comment]
只是爬虫图片，作为服务端的方法，不过爬虫出错就容易导致断连...
期待您的成果！

**Comment by CzaOrz** [comment]
多谢。

你的爬虫，是类似使用request爬虫获取图片然后传到前端吗，你不会这样写的把。
```
@ws.route('/test/example/1/1')
def example_1(request, data):
    import request
    pic = request.get(pic_url).content
    return {‘pic’: pic}
```

你可以在爬虫部分加个try，然后图片转base64，不然传不过去的。比如：
```
@ws.route('/test/example/1/1')
def example_1(request, data):
    try:
        import requests
        pic = requests.get(pic_url).content
    except:
        import traceback
        print(traceback.format_exc())
    return {'pic': pic_2_base64(pic)}
```

**Comment by liuzaozao7799** [comment]
好的，谢谢提醒。图片是下载到文件系统里，出错是因为爬取谷歌图片不太稳定...

**Comment by liuzaozao7799** [comment]
我遇到一个情况..像这种，如果没有return这一句，客户端会收到123和Hello Websocket；有return就收到123 456，而不会有Hello Websocket。在您的库的源码和客户端ws的源码都没找到相关的操作...为什么？
```
@ws.route('/test/example/1/1')
def example_1(request, data):
    request.ws_send('123')
    return '456'
```

**Comment by CzaOrz** [comment]
源码middleware.py - 104 行
```python
    @classmethod
    def process(cls, request, data, func=None):
        try:
            for process_input in cls.data_middleware['process_input']:
                data = process_input(request, data)
            data = (func(request, data) if func else data) or PublicConfig.DEFAULT_REPLY
            for process_output in cls.data_middleware['process_output']:
                data = process_output(request, data)
            return data
        except MiddlewareError:
            return ERROR_FLAG
```
这里的 PublicConfig.DEFAULT_REPLY 是默认回复内容

**Comment by liuzaozao7799** [comment]
多谢！
