### ISSUE TITLE
如何在子线程中运行websocket服务？

### ISSUE THREAD

**Issue by beenlyons** [czasg/pywss#23]
在做自动化测试时，我想启动一下临时用来做一个mock去测试我的程序
。此时我用threading去创建线程启动服务， 结果提示只能在主线程中运行 
ValueError: signal only works in main thread
有什么好的解决办法嘛？

**Comment by czasg** [comment]
使用版本 0.1.2，即 `pip3 install pywss==0.1.2`，此版本支持在子线程中启动服务。

**Comment by czasg** [comment]
晚点再修复下这个问题。

**Comment by czasg** [comment]
0.1.4已修复
