### ISSUE TITLE
如何与外网建立通信？

### ISSUE THREAD

**Issue by doubleLLL3** [czasg/Pywss#4]
我已经可以在外网登录我的客户端，那服务端和客户端的监听地址和端口该怎么设置呢？
现在服务端地址为0.0.0.0 端口为8866；客户端为localhost 端口为8866.
尝试修改服务端地址为外网IP，开启服务就会出错，说请求地址无效。
如果只修改客户端地址为外网IP，也无法连接上。

**Comment by CzaOrz** [comment]
你好，服务端总是0.0.0.0即可，需要修改客户端的ip地址。

如阿里云服务器为例：47.101.42.79:8866
然后还需要到阿里云官网开启8866端口
前端连接修改为：
```javascript
ws = new WebSocket("ws://47.101.42.79:8866/ws/chat")
```

ps：我近期引入了asyncio，如果是这方面导致的异常，建议退一个版本尝试。。

**Comment by CzaOrz** [comment]
你的问题可能是端口8866没有开启

**Comment by liuzaozao7799** [comment]
谢谢，我用的是内网映射，只有域名，那是把IP换成域名吗？然后http://去掉。
不过8866端口是固定的吗？可以修改服务器的端口吗，因为这个域名暂时只开放80端口或者10000以上的端口...

**Comment by CzaOrz** [comment]
啊，不好意思，我demo上没写，默认是8866端口，可以修改
```python
ws = Pyws(__name__, address='0.0.0.0', port=8866)
```

然后是客户端，用域名也是可以的，可以参考:
```javascript
ws = new WebSocket("ws://www.czasg.xyz:8866/ws/chat")
```

**Comment by liuzaozao7799** [comment]
现在端口映射只能使用80端口，而服务端把8866端口改为80端口会无法开启服务，说端口被占用，80端口应该不适合用来socket通信吧..
那我现在是换个端口映射的软件，或者花钱买个其他端口咯..

**Comment by CzaOrz** [comment]
这个操作我似乎没玩过，，可以去阿里买个学生云服务器，便宜的很

**Comment by liuzaozao7799** [comment]
我还是用的端口映射，换了一个软件，外网用的是端口是37609，服务端和客户端的端口都改为37609，然后客户端ws的地址改为我的映射域名，服务端为0.0.0.0.，但是还是连接不上。

如果将客户端的地址改为localhost，在本机上用localhost或者用外网登录客户端，都可以连接上，用另一台机器（不管在不在局域网里）用外网登录客户端都连接不上。

所以我在想是不是服务端地址0.0.0.0的问题呢还是其他的原因？我的外网只看到域名没看到绑定的IP地址。非常感谢您的耐心回答！

**Comment by CzaOrz** [comment]
这个我确实不是很擅长映射操作。
域名 映射到 IP 地址。这个过程一般是由DNS服务器实现的。

大致的流程是：浏览器获取域名，访问DNS服务器，拿到了IP地址，然后再根据IP地址进行寻址。

所以这里无论是填写域名还是IP地址都没有问题，填写localhost则直接在本机操作。
服务端的0.0.0.0表示监听所有的ip，是没有问题的。

**Comment by CzaOrz** [comment]
如果你仅仅是练习的话，倒是可以借你一台快过期得服务器玩下。

**Comment by liuzaozao7799** [comment]
太感谢了！我今天终于调试好了，原来Apache服务器需要对ws设置一个反向代理，虽然不是很懂原理...

**Comment by CzaOrz** [comment]
厉害了，，我还不会玩这个。不过我大致知道反向代理的原理...

反向代理：
分为多种，最常见的可以理解为“302重定向”，就是我不处理这次请求，转交给其他服务器处理的意思。

Apache的反向代理，应该是基于第7层交换技术的反向代理。
反向代理本身也是一个服务器，从socket角度讲就是挂起并监听某个端口，
当有请求来临的时候，读取请求并转发给其他端口，自己并不处理。

比如：反向代理监听80端口，监听到请求后立即将请求转到8866端口。

客户端与反向代理服务器建立连接，反向代理服务器又与内部其他服务建立连接。
你可能觉得多一次转交会更浪费，虽然确实是会浪费，但是从某种意义上来说可以“增大”流量。

**Comment by liuzaozao7799** [comment]
有点意思了，我今天再琢磨琢磨，多谢。:slightly_smiling_face:
